data:
    training:
        dataset:
            name: CelebA
            mean: [0.5084, 0.4224, 0.3768]
            std: [0.3048, 0.2824, 0.2808]
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5084, 0.4224, 0.3768]
                              std: [0.3048, 0.2824, 0.2808]
                target: null
            kwargs:
                use_download: false
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: true
                pin_memory: true
    validation:
        dataset:
            name: CelebA
            mean: [0.5084, 0.4224, 0.3768]
            std: [0.3048, 0.2824, 0.2808]
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5084, 0.4224, 0.3768]
                              std: [0.3048, 0.2824, 0.2808]
                target: null
            kwargs:
                use_download: false
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: false
                pin_memory: true
    test:
        dataset:
            name: CelebA
            mean: [0.5084, 0.4224, 0.3768]
            std: [0.3048, 0.2824, 0.2808]
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5084, 0.4224, 0.3768]
                              std: [0.3048, 0.2824, 0.2808]
                target: null
            kwargs:
                use_download: false
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: false
                pin_memory: true
model_discriminator:
    name: DiscriminatorDCGAN2d
    shape_input: [3, 128, 128]
    kwargs:
        num_channels_in: 3
        nums_channels_hidden: [32, 64, 128, 256, 512, 1024]
        num_channels_out: 1
        prob_dropout: 0.3
model_generator:
    name: GeneratorDCGAN2d
    shape_input: [128]
    kwargs:
        num_channels_in: 128
        nums_channels_hidden: [1024, 512, 256, 128, 64, 32]
        num_channels_out: 3
        use_normalize: true
        kwargs_normalize:
            mean: [0.4375, 0.4436, 0.4727]
            std: [0.1979, 0.2009, 0.1968]
measurers_discriminator:
    training:
        - name: Accuracy
          kwargs:
              task: binary
    validation:
        - name: Accuracy
          kwargs:
              task: binary
    test:
        - name: Accuracy
          kwargs:
              task: binary
measurers_generator:
    training:
        - name: FrechetInceptionDistance
          kwargs:
              use_unnormalize: true
              kwargs_unnormalize:
                  mean: [0.4375, 0.4436, 0.4727]
                  std: [0.1979, 0.2009, 0.1968]
              feature: 64
              normalize: true
              reset_real_features: true
    validation:
        - name: FrechetInceptionDistance
          kwargs:
              use_unnormalize: true
              kwargs_unnormalize:
                  mean: [0.4375, 0.4436, 0.4727]
                  std: [0.1979, 0.2009, 0.1968]
              feature: 64
              normalize: true
              reset_real_features: true
    test:
        - name: FrechetInceptionDistance
          kwargs:
              use_unnormalize: true
              kwargs_unnormalize:
                  mean: [0.4375, 0.4436, 0.4727]
                  std: [0.1979, 0.2009, 0.1968]
              feature: 64
              normalize: true
              reset_real_features: true
criterion:
    name: BCELoss
training:
    num_epochs: 20
    optimizer:
        name: Adam
        kwargs:
            lr: 3.0e-4
            weight_decay: 1.0e-3
            betas: [0.5, 0.9]
    scheduler:
        name: SequentialLR
        schedulers:
            - name: LinearLR
              kwargs:
                  start_factor: 0.333
                  end_factor: 1.0
                  total_iters: 5
            - name: ExponentialLR
              kwargs:
                  gamma: 0.9
        kwargs:
            milestones: [5]
    use_amp: true
    early_stopping:
        patience: 10
logging:
    tqdm:
        frequency: 10
    tensorboard:
        frequency: 1
        frequency_images: 300
    checkpoint:
        frequency: 10
