data:
    training:
        dataset:
            name: SVHN
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5, 0.5, 0.5]
                              std: [0.5, 0.5, 0.5]
                target: null
            kwargs:
                use_download: false
                ratio_validation_to_training: 0.2
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: true
                pin_memory: true
    validation:
        dataset:
            name: SVHN
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5, 0.5, 0.5]
                              std: [0.5, 0.5, 0.5]
                target: null
            kwargs:
                use_download: false
                ratio_validation_to_training: 0.2
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: false
                pin_memory: true
    test:
        dataset:
            name: SVHN
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5, 0.5, 0.5]
                              std: [0.5, 0.5, 0.5]
                target: null
            kwargs:
                use_download: false
                ratio_validation_to_training: 0.2
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: false
                pin_memory: true
model:
    name: GAN
    shape_input: [3, 32, 32]
    kwargs:
        num_channels_latent: 64
        num_channels_real: 3
        num_channels_out: 1
        name_generator: GeneratorDCGAN2d
        kwargs_generator:
            nums_channels_hidden: [512, 256, 128, 64]
        name_discriminator: DiscriminatorDCGAN
        kwargs_discriminator:
            nums_channels_hidden: [64, 128, 256, 512]
            prob_dropout: 0.3
        use_normalize: true
        kwargs_normalize:
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
measurers:
    training:
        - name: Select
          kwargs:
              key: "prediction"
              name_module: SmoothL1Loss
              kwargs_module:
                  beta: 1.0
        - name: ELBOGaussian
          kwargs: {}
    validation:
        - name: Select
          kwargs:
              key: "prediction"
              name_module: SmoothL1Loss
              kwargs_module:
                  beta: 1.0
        - name: ELBOGaussian
          kwargs: {}
        - name: Select
          kwargs:
              key: "prediction"
              name_module: FrechetInceptionDistance
              kwargs_module:
                  use_unnormalize: true
                  kwargs_unnormalize:
                      mean: [0.5, 0.5, 0.5]
                      std: [0.5, 0.5, 0.5]
                  feature: 64
                  normalize: true
                  reset_real_features: false
    test:
        - name: Select
          kwargs:
              key: "prediction"
              name_module: SmoothL1Loss
              kwargs_module:
                  beta: 1.0
        - name: ELBOGaussian
          kwargs: {}
        - name: Select
          kwargs:
              key: "prediction"
              name_module: FrechetInceptionDistance
              kwargs_module:
                  use_unnormalize: true
                  kwargs_unnormalize:
                      mean: [0.5, 0.5, 0.5]
                      std: [0.5, 0.5, 0.5]
                  feature: 64
                  normalize: true
                  reset_real_features: false
criterion:
    name: SumWeighted
    modules:
        - name: Select
          kwargs:
              key: "prediction"
              name_module: SmoothL1Loss
              kwargs_module:
                  beta: 1.0
        - name: ELBOGaussian
          kwargs: {}
    kwargs:
        weights: [1.0, 1.0e-3]
training:
    num_epochs: 20
    optimizer:
        name: Adam
        kwargs:
            lr: 3.0e-4
            weight_decay: 1.0e-3
            betas: [0.5, 0.9]
    scheduler:
        # TODO
        name: SequentialLR
        dynamic:
        schedulers:
            - name: LinearLR
              kwargs:
                  start_factor: 0.333
                  end_factor: 1.0
                  total_iters: 5
            - name: ExponentialLR
              kwargs:
                  gamma: 0.9
        kwargs:
            milestones: [5]
    use_amp: true
    early_stopping:
        patience: 10
logging:
    tqdm:
        frequency: 10
    tensorboard:
        frequency: 1
    checkpoint:
        frequency: 10
