data:
    training:
        dataset:
            name: SVHN
            mean: [0.4375, 0.4436, 0.4727]
            std: [0.1979, 0.2009, 0.1968]
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.4375, 0.4436, 0.4727]
                              std: [0.1979, 0.2009, 0.1968]
                target: null
            kwargs:
                use_download: false
                ratio_validation_to_training: 0.2
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: true
                pin_memory: true
    validation:
        dataset:
            name: SVHN
            mean: [0.4375, 0.4436, 0.4727]
            std: [0.1979, 0.2009, 0.1968]
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.4375, 0.4436, 0.4727]
                              std: [0.1979, 0.2009, 0.1968]
                target: null
            kwargs:
                use_download: false
                ratio_validation_to_training: 0.2
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: false
                pin_memory: true
    test:
        dataset:
            name: SVHN
            mean: [0.4375, 0.4436, 0.4727]
            std: [0.1979, 0.2009, 0.1968]
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.4375, 0.4436, 0.4727]
                              std: [0.1979, 0.2009, 0.1968]
                target: null
            kwargs:
                use_download: false
                ratio_validation_to_training: 0.2
        dataloader:
            kwargs:
                batch_size: 128
                shuffle: false
                pin_memory: true
model_discriminator:
    name: DiscriminatorDCGAN
    shape_input: [3, 32, 32]
    kwargs:
        num_channel_in: 3
        nums_channels_hidden: [64, 128, 256, 512]
        num_channel_out: 1
        prob_dropout: 0.3
model_generator:
    name: GeneratorDCGAN
    shape_input: [64]
    kwargs:
        num_channel_in: 64
        nums_channels_hidden: [512, 256, 128, 64]
        num_channel_out: 3
        use_normalize: true
        kwargs_normalize:
            mean: [0.4375, 0.4436, 0.4727]
            std: [0.1979, 0.2009, 0.1968]
measurers_discriminator:
    training:
        - name: Accuracy
          kwargs:
              task: multiclass
              num_classes: 10
    validation:
        - name: Accuracy
          kwargs:
              task: multiclass
              num_classes: 10
    test:
        - name: Accuracy
          kwargs:
              task: multiclass
              num_classes: 10
measurers_generator:
    training:
        - name: FrechetInceptionDistance
          kwargs:
              use_unnormalize: true
              kwargs_unnormalize:
                  mean: [0.4375, 0.4436, 0.4727]
                  std: [0.1979, 0.2009, 0.1968]
              feature: 64
              normalize: true
              reset_real_features: true
    validation:
        - name: FrechetInceptionDistance
          kwargs:
              use_unnormalize: true
              kwargs_unnormalize:
                  mean: [0.4375, 0.4436, 0.4727]
                  std: [0.1979, 0.2009, 0.1968]
              feature: 64
              normalize: true
              reset_real_features: true
    test:
        - name: FrechetInceptionDistance
          kwargs:
              use_unnormalize: true
              kwargs_unnormalize:
                  mean: [0.4375, 0.4436, 0.4727]
                  std: [0.1979, 0.2009, 0.1968]
              feature: 64
              normalize: true
              reset_real_features: true
criterion:
    name: BCELoss
training:
    num_epochs: 20
    optimizer:
        name: Adam
        kwargs:
            lr: 3.0e-4
            weight_decay: 1.0e-3
            betas: [0.5, 0.9]
    scheduler:
        name: SequentialLR
        schedulers:
            - name: LinearLR
              kwargs:
                  start_factor: 0.333
                  end_factor: 1.0
                  total_iters: 5
            - name: ExponentialLR
              kwargs:
                  gamma: 0.9
        kwargs:
            milestones: [5]
    use_amp: true
    early_stopping:
        patience: 10
logging:
    tqdm:
        frequency: 10
    tensorboard:
        frequency: 1
    checkpoint:
        frequency: 10
