data:
    train:
        dataset:
            name: StanfordCars
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: RandomResizedCrop
                          kwargs:
                              size: [224, 224]
                        - name: RandomHorizontalFlip
                          kwargs:
                              p: 0.5
                        - name: RandomRotation
                          kwargs:
                              degrees: [-45, 45]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: ColorJitter
                          kwargs:
                              brightness: [0.5, 1.5]
                              contrast: [0.8, 1.2]
                              saturation: [0.8, 1.2]
                              hue: [-0.2, 0.2]
                        - name: GaussianNoise
                          kwargs:
                              mean: 0.0
                              std: 0.1
                        - name: Clip
                          kwargs:
                              min: 0.0
                              max: 1.0
                        - name: Normalize
                          kwargs:
                              mean: [0.485, 0.456, 0.406]
                              std: [0.229, 0.224, 0.225]
                target: null
            kwargs:
                ratio_validate_to_train: 0.8
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
            collation:
                name: default
                kwargs:
                    dict_transform:
                        name: RandomChoice
                        kwargs: {}
                        transforms:
                            - name: MixUp
                              kwargs:
                                  num_classes: 196
                            - name: CutMix
                              kwargs:
                                  num_classes: 196
    validate:
        dataset:
            name: StanfordCars
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: Resize
                          kwargs:
                              size: [256, 256]
                        - name: CenterCrop
                          kwargs:
                              size: [224, 224]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.485, 0.456, 0.406]
                              std: [0.229, 0.224, 0.225]
                target: null
            kwargs:
                ratio_validate_to_train: 0.8
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
    test:
        dataset:
            name: StanfordCars
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: Resize
                          kwargs:
                              size: [256, 256]
                        - name: CenterCrop
                          kwargs:
                              size: [224, 224]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.485, 0.456, 0.406]
                              std: [0.229, 0.224, 0.225]
                target: null
            kwargs:
                ratio_validate_to_train: 0.8
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
criterion:
    name: CrossEntropyLoss
    kwargs: {}
measurers:
    - name: Accuracy
      kwargs: {}
model:
    name: mobilenet_v3_large
    shape_input: [3, 224, 224]
    kwargs:
        weights: "DEFAULT"
        progress: false
    transfer:
        epochs_freeze: 0
        layers:
            - name: classifier
              model:
                  name: MLP
                  kwargs:
                      num_channels_in: 960
                      nums_channels_hidden: [1280]
                      num_channels_out: 196
                      name_layer_act: Hardswish
                      prob_dropout: 0.2
                      use_bias: true
                      inplace: true
frequency_log: 5
frequency_checkpoint: 50
training:
    num_epochs: 100
    optimizer:
        name: Adam
        kwargs:
            lr: 5.0e-4
            weight_decay: 0.02
visualization:
    kwargs_unnormalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
