data:
    train:
        dataset:
            name: KTH
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: RandomHorizontalFlip
                          kwargs:
                              p: 0.5
                        - name: RandomRotation
                          kwargs:
                              degrees: [-10.0, 10.0]
                        - name: ColorJitter
                          kwargs:
                              brightness: [0.5, 1.5]
                              contrast: [0.8, 1.2]
                              saturation: 0
                              hue: 0
                        - name: GaussianNoise
                          kwargs:
                              mean: 0.0
                              std: 0.05
                        - name: Clip
                          kwargs:
                              min: 0.0
                              max: 1.0
                target: null
            kwargs:
                len_sequence: 15
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
                pin_memory: true
    validate:
        dataset:
            name: KTH
            transform:
                features:
                    name: ToDtype
                    kwargs:
                        dtype: float32
                        scale: true
                target: null
            kwargs:
                len_sequence: 15
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
                pin_memory: true
    test:
        dataset:
            name: KTH
            transform:
                features:
                    name: ToDtype
                    kwargs:
                        dtype: float32
                        scale: true
                target: null
            kwargs:
                len_sequence: 15
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
                pin_memory: true
criterion:
    name: CrossEntropyLoss
    kwargs: {}
measurers:
    - name: Accuracy
      kwargs: {}
model:
    name: ResNet3d
    shape_input: [15, 1, 64, 64]
    kwargs:
        num_channels_in: 15
        num_channels_out: 6
        nums_layers: [2, 2, 2, 2]
        block: BasicBlock
frequency_log: 5
frequency_checkpoint: 10
training:
    num_epochs: 50
    optimizer:
        name: Adam
        kwargs:
            lr: 3.0e-4
            weight_decay: 1.0e-3
    scheduler:
        name: ReduceLROnPlateau
        kwargs:
            factor: 0.5
            patience: 5
