data:
    training:
        dataset:
            name: CelebA
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                target: null
            kwargs:
                use_download: true
                types_target_tv: []
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
                pin_memory: true
    validation:
        dataset:
            name: CelebA
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                target: null
            kwargs:
                use_download: true
                types_target_tv: []
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
                pin_memory: true
    test:
        dataset:
            name: CelebA
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                target: null
            kwargs:
                use_download: true
                types_target_tv: []
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
                pin_memory: true
