data:
    training:
        dataset:
            name: CelebA
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5084, 0.4224, 0.3768]
                              std: [0.3048, 0.2824, 0.2808]
                target: null
            kwargs:
                use_download: true
                types_target_tv: []
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
                pin_memory: true
    validation:
        dataset:
            name: CelebA
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5084, 0.4224, 0.3768]
                              std: [0.3048, 0.2824, 0.2808]
                target: null
            kwargs:
                use_download: true
                types_target_tv: []
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
                pin_memory: true
    test:
        dataset:
            name: CelebA
            transform:
                features:
                    name: Compose
                    kwargs: {}
                    transforms:
                        - name: PILToTensor
                          kwargs: {}
                        - name: CenterCrop
                          kwargs:
                              size: [178, 178]
                        - name: Resize
                          kwargs:
                              size: [128, 128]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                        - name: Normalize
                          kwargs:
                              mean: [0.5084, 0.4224, 0.3768]
                              std: [0.3048, 0.2824, 0.2808]
                target: null
            kwargs:
                use_download: true
                types_target_tv: []
                use_features_as_target: true
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
                pin_memory: true
model:
    name: VAEConv
    shape_input: [15, 1, 64, 64]
    kwargs:
        name_encoder: CNN2dEncoder
        kwargs_encoder:
            shape_input: [1, 64, 64]
            nums_channels_hidden_body: [64, 128, 256, 512]
            num_channels_out: 512
            kwargs_body:
                shape_kernel_conv: [5, 5]
                shape_kernel_pool: [2, 2]
                name_layer_act: LeakyReLU
                name_layer_norm: BatchNorm2d
                name_layer_pool: MaxPool2d
                kwargs_conv:
                    padding: same
                kwargs_pool: {}
        name_rnn: LSTM
        kwargs_rnn:
            num_channels_in: 512
            num_channels_out: 512
            num_cells: 5
            name_func_init: kaiming_uniform_
        name_head: MLP
        kwargs_head:
            num_channels_in: 512
            nums_channels_hidden: [256]
            num_channels_out: 6
            name_layer_act: LeakyReLU
            name_layer_norm: BatchNorm1d
            prob_dropout: 0.1
criterion:
    - name: SmoothL1Loss
      kwargs:
          beta: 1.0
      weight: 1.0
    - name: ELBOGaussian
      kwargs: {}
      weight: 1e-3
measurement:
    - name: SmoothL1Loss
      kwargs:
          beta: 1.0
      weight: 1.0
    - name: ELBOGaussian
      kwargs: {}
      weight: 1e-3
    - name: FrechetInceptionDistance
      kwargs: {}
training:
    num_epochs: 50
    optimizer:
        name: Adam
        kwargs:
            lr: 3.0e-4
            weight_decay: 1.0e-3
    scheduler:
        name: ReduceLROnPlateau
        kwargs:
            factor: 0.5
            patience: 5
visualization:
    kwargs_unnormalize:
        mean: [0.5084, 0.4224, 0.3768]
        std: [0.3048, 0.2824, 0.2808]
logging:
    tqdm:
        frequency: 5
    tensorboard:
        frequency: 1
    checkpoint:
        frequency: 10
