data:
    train:
        dataset:
            name: SVHN
            transforms:
                features:
                    - name: ToTensor
                      kwargs: {}
                target: []
            kwargs:
                download: false
                ratio_train2validate: 0.83
        dataloader:
            kwargs:
                batch_size: 256
                shuffle: true
    validate:
        dataset:
            name: SVHN
            transforms:
                features:
                    - name: ToTensor
                      kwargs: {}
                target: []
            kwargs:
                download: false
                ratio_train2validate: 0.83
        dataloader:
            kwargs:
                batch_size: 256
                shuffle: false
    test:
        dataset:
            name: SVHN
            transforms:
                features:
                    - name: ToTensor
                      kwargs: {}
                target: []
            kwargs:
                download: false
                ratio_train2validate: 0.83
        dataloader:
            kwargs:
                batch_size: 256
                shuffle: false
criterion:
    name: CrossEntropyLoss
    kwargs: {}
measurers:
    - name: Accuracy
      kwargs: {}
model:
    name: CNN2d
    kwargs:
        shape_input: [3, 32, 32]
        nums_channels_hidden_body: [32, 64, 128]
        nums_channels_hidden_head: []
        num_channels_out: 10
        kwargs_body:
            shape_kernel_conv: [5, 5]
            shape_kernel_pool: [2, 2]
            name_layer_act: ReLU
            name_layer_norm: InstanceNorm2d
            name_layer_pool: MaxPool2d
            kwargs_conv:
                padding: same
                padding_mode: reflect
            kwargs_pool: {}
        kwargs_head:
            name_layer_act: ReLU
            use_bias: true
frequency_log: 10
frequency_checkpoint: 50
training:
    num_epochs: 100
    optimizer:
        name: Adam
        kwargs:
            lr: 1.0e-4
optimization_hyperparams:
    direction: maximize
    metric: Accuracy
    params_to_optimize:
        - name: Learning rate
          type: float
          kwargs:
              low: 1.0e-5
              high: 1.0e-3
              log: true
          path_in_config: [training, lr]
        - name: Hidden dimensions of body
          type: list
          kwargs:
              choices:
                  - []
                  - [16]
                  - [64]
                  - [128]
                  - [16, 32]
                  - [32, 64]
                  - [16, 32, 64]
                  - [32, 64, 128]
                  - [64, 128, 256]
          path_in_config: [model, kwargs, nums_channels_hidden_body]
        - name: Hidden dimensions of head
          type: list
          kwargs:
              choices:
                  - []
                  - [64]
                  - [128]
                  - [256]
                  - [512]
                  - [64, 32]
                  - [128, 64]
                  - [256, 128]
          path_in_config: [model, kwargs, nums_channels_hidden_head]
        - name: Convolution kernel shape
          type: list
          kwargs:
              choices:
                  - [1, 1]
                  - [3, 3]
                  - [5, 5]
                  - [7, 7]
          path_in_config: [model, kwargs, kwargs_body, shape_kernel_conv]
        - name: Normalization layer in body
          type: categorical
          kwargs:
              choices: [null, BatchNorm2d, InstanceNorm2d]
          path_in_config: [model, kwargs, kwargs_body, name_layer_norm]
        - name: Activation layer in body
          type: categorical
          kwargs:
              choices: [ReLU, LeakyReLU, Softplus]
          path_in_config: [model, kwargs, kwargs_body, name_layer_act]
        - name: Pooling layer in body
          type: categorical
          kwargs:
              choices: [MaxPool2d, AvgPool2d]
          path_in_config: [model, kwargs, kwargs_body, name_layer_pool]
        - name: Usage of bias in convolution
          type: categorical
          kwargs:
              choices: [false, true]
          path_in_config: [model, kwargs, kwargs_body, kwargs_conv, bias]
        - name: Padding in convolution
          type: categorical
          kwargs:
              choices: [valid, same]
          path_in_config: [model, kwargs, kwargs_body, kwargs_conv, padding]
        - name: Padding mode in convolution
          type: categorical
          kwargs:
              choices: [zeros, reflect, replicate, circular]
          path_in_config:
              [model, kwargs, kwargs_body, kwargs_conv, padding_mode]
